Add circle ci config
prose/gatekeeper pull request #45
Opened 2017-11-06 10:02 UTC by dereklieu

2017-11-06 10:07 UTC, dereklieu commented
Note, I've just set the default branch to `development` since that's where the majority of pull requests should be made against.

2017-11-06 20:06 UTC, kriswep requested changes
Using circleci would work great imo. 
We could also consider adding a badge...

I was just wondering over the choosen node image, please see my line comment.

2017-11-06 20:06 UTC, kriswep commented on .circleci/config.yml
> +      - image: developmentseed/circleci:node8.4-python2.7
Any specific reason you choosed this image over the 'official' circleci node image (https://hub.docker.com/r/circleci/node/)? Is that for python?
I think using image 
`- image: circleci/node:8` or `- image: circleci/node:8.9` would be a good call.
Please note that v8.4 is  actually not LTS (8.9.0 is).

2017-11-08 23:15 UTC, dereklieu commented
Yeah good point, I changed it to `circleci/node:8.9`

2017-11-08 23:15 UTC, merged